spring.application.name=API-REST-Finance
spring.datasource.url=jdbc:postgresql://ep-plain-night-asdh10n4-pooler.c-4.eu-central-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_Q2qs8UPboapi&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Q2qs8UPboapi
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create-drop