spring.application.name=API-REST-Finance
#spring.datasource.url=jdbc:postgresql://ep-plain-night-asdh10n4-pooler.c-4.eu-central-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_Q2qs8UPboapi&sslmode=require&channelBinding=require
spring.datasource.url=jdbc:postgresql://ep-plain-night-asdh10n4-pooler.c-4.eu-central-1.aws.neon.tech/neondb?user=${DB_USER}&password=${DB_PASSWORD}&sslmode=require&channelBinding=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=none